name: PoolParty Deploy

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  release:
    types: [published, created, edited]
    
jobs:
  test:
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: r2d
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: install yarn
      run: npm install -g yarn
      
    - name: yarn install, build, and test
      run: |
        yarn install  --frozen-lockfile
        yarn build
        yarn test
   
    - name: Making your code pretty. 
      run: | 
        yarn format
        
    - name: Label this PR with automerge
      uses: TimonVS/pr-labeler-action@v3.1.0
      with:
        configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        


