name: PoolParty Deploy

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: install yarn
      run: npm install -g yarn
      
    - name: yarn install, build, and test
      run: |
        yarn install  --frozen-lockfile
        yarn build
        yarn test
   
    - name: Prettify the JS Code
      uses: creyD/prettier_action@v2.1
      with:
        prettier_options: 'prettier --no-bracket-spacing --trailing-comma none --jsx-bracket-same-line --write \"**/*.{js,jsx,json,md, mdx}\"'
        branch: ${{ github.head_ref }}
        
    - name: Label this PR with automerge
      uses: TimonVS/pr-labeler-action@v3
      with:
        configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        


